project_name: dtom
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64

archives:
  - name_template: "{{.Binary}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: Giuseppe Rizzi <giusrizzi_AT_gmail.com>
    description: DynamoDB JSONs into MongoDB importer.
    homepage: https://github.com/gRizzlyGR/dtom
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
